=== flarebyte/bubblegum-entity/script/schema/merged.schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/Module",
  "description": "Schema for the model once it has been generated an merged",
  "definitions": {
    "Module": {
      "type": "object",
      "description": "Root object after merging",
      "additionalProperties": false,
      "properties": {
        "functions": {
          "type": "array",
          "title": "Elm functions",
          "items": {
            "$ref": "#/definitions/Function"
          }
        },
        "moduleName": {
          "type": "string",
          "description": "The name of the Elm module"
        },
        "packageNameDot": {
          "type": "string",
          "description": "The Elm package name separated by dots",
          "examples": ["Bubblegum.Entity"]
        },
        "oks": {
          "type": "array",
          "description": "The list of  ok variables for indicating success that are used for testing the module",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["functions", "moduleName", "oks", "packageNameDot"],
      "title": "Elm Module"
    },
    "Function": {
      "type": "object",
      "description": "Description of an Elm function",
      "additionalProperties": false,
      "properties": {
        "functionName": {
          "type": "string",
          "title": "Name of the Elm function"
        },
        "params": {
          "type": "array",
          "title": "List of parameters for the Elm function",
          "items": {
            "$ref": "#/definitions/Param"
          }
        },
        "returned": {
          "type": "string",
          "description": "Type returned by the function"
        },
        "states": {
          "type": "array",
          "description": "List of all the states that the unit tests need to support for a function",
          "items": {
            "$ref": "#/definitions/State"
          }
        },
        "ok": {
          "type": "string",
          "description": "Value to expect for success"
        },
        "noDescribeComma": {
          "type": "boolean",
          "description": "Set to true if the function is the last one and we should omit the coma"
        }
      },
      "required": ["functionName", "params", "returned"],
      "title": "Elm function"
    },
    "Param": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "paramName": {
          "type": "string",
          "title": "Name of the parameter"
        },
        "paramType": {
          "type": "string",
          "title": "Type of the parameter"
        }
      },
      "required": ["paramName", "paramType"],
      "title": "Function parameter"
    },
    "State": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "stateName": {
          "type": "string",
          "title": "Name of the state"
        }
      },
      "required": ["stateName"],
      "title": "State that need to be tested"
    }
  }
}

=== flarebyte/bubblegum-entity/generated/outcome.json
{
  "functions": [
    {
      "functionName": "withDefault",
      "params": [
        {
          "paramName": "def",
          "paramType": "a"
        },
        {
          "paramName": "outcome",
          "paramType": "Outcome a"
        }
      ],
      "returned": "Outcome a",
      "states": [
        {
          "stateName": "valid"
        },
        {
          "stateName": "none"
        }
      ],
      "ok": "ok2"
    },
    {
      "functionName": "map",
      "params": [
        {
          "paramName": "func",
          "paramType": "(a -> value)"
        },
        {
          "paramName": "ra",
          "paramType": "Outcome a"
        }
      ],
      "returned": "Outcome value",
      "states": [
        {
          "stateName": "valid"
        },
        {
          "stateName": "none"
        },
        {
          "stateName": "warning"
        }
      ],
      "ok": "ok2"
    },
    {
      "functionName": "map2",
      "params": [
        {
          "paramName": "func",
          "paramType": "(a -> b @ value)"
        },
        {
          "paramName": "ra",
          "paramType": "Outcome a"
        },
        {
          "paramName": "rb",
          "paramType": "Outcome b"
        }
      ],
      "returned": "Outcome value",
      "states": [
        {
          "stateName": "valid"
        },
        {
          "stateName": "none"
        },
        {
          "stateName": "warning"
        }
      ],
      "ok": "ok2"
    },
    {
      "functionName": "check",
      "params": [
        {
          "paramName": "checker",
          "paramType": "(a -> Bool)"
        },
        {
          "paramName": "warnMsg",
          "paramType": "String"
        },
        {
          "paramName": "ra",
          "paramType": "Outcome a"
        }
      ],
      "returned": "Outcome a",
      "states": [
        {
          "stateName": "valid"
        },
        {
          "stateName": "none"
        },
        {
          "stateName": "warning"
        },
        {
          "stateName": "check failed"
        }
      ],
      "ok": "ok2"
    },
    {
      "functionName": "checkOrNone",
      "params": [
        {
          "paramName": "checker",
          "paramType": "(a -> Bool)"
        },
        {
          "paramName": "ra",
          "paramType": "Outcome a"
        }
      ],
      "returned": "Outcome a",
      "states": [
        {
          "stateName": "valid"
        },
        {
          "stateName": "check failed"
        },
        {
          "stateName": "warning"
        }
      ],
      "ok": "ok2"
    },
    {
      "functionName": "trueMapToConstant",
      "params": [
        {
          "paramName": "const",
          "paramType": "a"
        },
        {
          "paramName": "outcome",
          "paramType": "Outcome Bool"
        }
      ],
      "returned": "Outcome a",
      "states": [
        {
          "stateName": "true"
        },
        {
          "stateName": "false"
        }
      ],
      "ok": "ok2"
    },
    {
      "functionName": "or",
      "params": [
        {
          "paramName": "ma",
          "paramType": "Outcome a"
        },
        {
          "paramName": "mb",
          "paramType": "Outcome a"
        }
      ],
      "returned": "Outcome a",
      "states": [
        {
          "stateName": "first"
        },
        {
          "stateName": "second"
        }
      ],
      "ok": "ok2"
    },
    {
      "functionName": "fromMaybe",
      "params": [
        {
          "paramName": "maybe",
          "paramType": "Maybe a"
        }
      ],
      "returned": "Outcome a",
      "states": [
        {
          "stateName": "valid"
        },
        {
          "stateName": "none"
        }
      ],
      "ok": "ok2"
    },
    {
      "functionName": "toMaybe",
      "params": [
        {
          "paramName": "outcome",
          "paramType": "Outcome a"
        }
      ],
      "returned": "Maybe a",
      "states": [
        {
          "stateName": "just"
        },
        {
          "stateName": "nothing"
        }
      ],
      "ok": "ok1"
    },
    {
      "functionName": "isValid",
      "params": [
        {
          "paramName": "outcome",
          "paramType": "Outcome a"
        }
      ],
      "returned": "Bool"
    },
    {
      "functionName": "isNone",
      "params": [
        {
          "paramName": "outcome",
          "paramType": "Outcome a"
        }
      ],
      "returned": "Bool"
    },
    {
      "functionName": "isWarning",
      "params": [
        {
          "paramName": "outcome",
          "paramType": "Outcome a"
        }
      ],
      "returned": "Bool"
    }
  ],
  "moduleName": "Outcome",
  "packageNameDot": "Bubblegum.Entity",
  "oks": [
    "ok1",
    "ok2"
  ]
}
