=== flarebyte/bubblegum-entity/script/schema/module.schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/Module",
  "description": "Schema for adding metadata to a module",
  "definitions": {
    "Module": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "moduleName": {
          "type": "string",
          "description": "The name of the Elm module"
        },
        "packageNameDot": {
          "type": "string",
          "description": "The Elm package name separated by dots",
          "examples": ["Bubblegum.Entity"]
        },
        "oks": {
          "type": "array",
          "description": "The list of  ok variables for indicating success that are used for testing the module",
          "items": {
            "type": "string"
          }
        },
        "functions": {
          "$ref": "#/definitions/Functions"
        }
      },
      "required": ["functions", "moduleName", "oks", "packageNameDot"],
      "title": "Description of a module"
    },
    "Functions": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "__merging_primary_key": {
          "constant": "functionName",
          "description": "Utility key that is used for merging by baldrick-whisker"
        }
      },
      "patternProperties": {
        "^[A-Za-z0-9]+": {
          "$ref": "#/definitions/Function"
        }
      },
      "required": ["__merging_primary_key"],
      "title": "List of Elm functions"
    },
    "Function": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "states": {
          "type": "array",
          "description": "List of all the states that the unit tests need to support for a function",
          "items": {
            "$ref": "#/definitions/State"
          }
        },
        "ok": {
          "type": "string",
          "description": "Value to expect for success"
        }
      },
      "required": ["ok", "states"],
      "title": "Metadata for function",
      "description": "Additional metadata for the Elm function"
    },
    "State": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "stateName": {
          "type": "string",
          "title": "Name of the state"
        }
      },
      "required": ["stateName"],
      "title": "State",
      "description": "State that need to be tested"
    }
  }
}

=== flarebyte/bubblegum-entity/script/data/module/attribute.json
{
  "moduleName": "Attribute",
  "packageNameDot": "Bubblegum.Entity",
  "oks": ["ok2"],
  "functions": {
    "__merging_primary_key": "functionName",
    "findAttributeByKey": {
      "states": [
        {
          "stateName": "just model"
        },
        {
          "stateName": "nothing"
        }
      ],
      "ok": "ok2"
    },
    "findAttributeFirstValueByKey": {
      "states": [
        {
          "stateName": "just string"
        },
        {
          "stateName": "nothing"
        }
      ],
      "ok": "ok2"
    },
    "findOutcomeByKey": {
      "states": [
        {
          "stateName": "valid outcome"
        },
        {
          "stateName": "none outcome"
        }
      ],
      "ok": "ok2"
    },
    "findOutcomeByKeyTuple": {
      "states": [
        {
          "stateName": "valid outcome"
        },
        {
          "stateName": "outcome with first none"
        }
      ],
      "ok": "ok2"
    },
    "deleteAttributeByKey": {
      "states": [
        {
          "stateName": "list"
        },
        {
          "stateName": "empty list"
        }
      ],
      "ok": "ok2"
    },
    "replaceAttributeByKey": {
      "states": [
        {
          "stateName": "list"
        },
        {
          "stateName": "empty list"
        }
      ],
      "ok": "ok2",
      "noDescribeComma": true
    }
  }
}

=== flarebyte/bubblegum-entity/script/data/module/validation.json
{
  "moduleName": "Validation",
  "packageNameDot": "Bubblegum.Entity",
  "oks": ["ok1"],
  "functions": {
    "__merging_primary_key": "functionName",
    "asIntRange": {
      "states": [{ "stateName": "valid" }, { "stateName": "invalid" }],
      "ok": "ok1"
    },
    "asFloatRange": {
      "states": [{ "stateName": "valid" }, { "stateName": "invalid" }],
      "ok": "ok1"
    },
    "withinIntRange": {
      "states": [{ "stateName": "valid" }, { "stateName": "invalid" }],
      "ok": "ok1"
    },
    "_withinFloatRange": {
      "states": [{ "stateName": "valid" }, { "stateName": "invalid" }],
      "ok": "ok1"
    },
    "listStrictlyLessThan": {
      "states": [{ "stateName": "valid" }, { "stateName": "invalid" }],
      "ok": "ok1"
    },
    "listStrictlyMoreThan": {
      "states": [{ "stateName": "valid" }, { "stateName": "invalid" }],
      "ok": "ok1"
    },
    "matchAbsoluteUrl": {
      "states": [{ "stateName": "valid" }, { "stateName": "invalid" }],
      "ok": "ok1"
    },
    "matchEnum": {
      "states": [{ "stateName": "valid" }, { "stateName": "invalid" }],
      "ok": "ok1"
    },
    "matchCompactUri": {
      "states": [{ "stateName": "valid" }, { "stateName": "invalid" }],
      "ok": "ok1"
    },
    "stringStartsWith": {
      "states": [{ "stateName": "valid" }, { "stateName": "invalid" }],
      "ok": "ok1"
    },
    "withinStringCharsRange": {
      "states": [{ "stateName": "valid" }, { "stateName": "invalid" }],
      "ok": "ok1",
      "noDescribeComma": true
    }
  }
}

=== flarebyte/bubblegum-entity/script/data/outcome.json
{
  "moduleName": "Outcome",
  "packageNameDot": "Bubblegum.Entity",
  "oks": ["ok1", "ok2"],
  "functions": {
    "__merging_primary_key": "functionName",
    "withDefault": {
      "states": [{ "stateName": "valid" }, { "stateName": "none" }],
      "ok": "ok2"
    },
    "map": {
      "states": [
        { "stateName": "valid" },
        { "stateName": "none" },
        { "stateName": "warning" }
      ],
      "ok": "ok2"
    },
    "map2": {
      "states": [
        { "stateName": "valid" },
        { "stateName": "none" },
        { "stateName": "warning" }
      ],
      "ok": "ok2"
    },
    "check": {
      "states": [
        { "stateName": "valid" },
        { "stateName": "none" },
        { "stateName": "warning" },
        { "stateName": "check failed" }
      ],
      "ok": "ok2"
    },
    "checkOrNone": {
      "states": [
        { "stateName": "valid" },
        { "stateName": "check failed" },
        { "stateName": "warning" }
      ],
      "ok": "ok2"
    },
    "trueMapToConstant": {
      "states": [{ "stateName": "true" }, { "stateName": "false" }],
      "ok": "ok2"
    },
    "or": {
      "states": [{ "stateName": "first" }, { "stateName": "second" }],
      "ok": "ok2"
    },
    "fromMaybe": {
      "states": [{ "stateName": "valid" }, { "stateName": "none" }],
      "ok": "ok2"
    },
    "toMaybe": {
      "states": [{ "stateName": "just" }, { "stateName": "nothing" }],
      "ok": "ok1"
    }
  }
}
